package com.netec.exams.examrequest;
import jakarta.servlet.http.HttpServletRequest;import java.net.URI;import java.time.Instant;import java.util.*;import org.springframework.http.*;import org.springframework.orm.ObjectOptimisticLockingFailureException;import org.springframework.web.bind.MethodArgumentNotValidException;import org.springframework.web.bind.annotation.*;
@RestControllerAdvice class ApiExceptionHandler {
 @ExceptionHandler(MethodArgumentNotValidException.class)ResponseEntity<ProblemDetail> validation(MethodArgumentNotValidException e,HttpServletRequest r){var p=problem(400,"VALIDATION_FAILED","La solicitud contiene datos inválidos",r);p.setProperty("fieldErrors",e.getBindingResult().getFieldErrors().stream().map(f->Map.of("field",f.getField(),"code","INVALID_VALUE","message",Objects.requireNonNullElse(f.getDefaultMessage(),"Valor inválido"))).toList());return ResponseEntity.badRequest().body(p);}
 @ExceptionHandler(ObjectOptimisticLockingFailureException.class)ResponseEntity<ProblemDetail> conflict(Exception e,HttpServletRequest r){return ResponseEntity.status(409).body(problem(409,"VERSION_CONFLICT","El borrador cambió en otra sesión",r));}
 @ExceptionHandler(InvalidStateException.class)ResponseEntity<ProblemDetail> state(Exception e,HttpServletRequest r){return ResponseEntity.status(409).body(problem(409,"INVALID_STATE_TRANSITION","La solicitud ya no es editable",r));}
 @ExceptionHandler(NotFoundException.class)ResponseEntity<ProblemDetail> missing(Exception e,HttpServletRequest r){return ResponseEntity.status(404).body(problem(404,"RESOURCE_NOT_FOUND","No se encontró el recurso",r));}
 @ExceptionHandler(IllegalArgumentException.class)ResponseEntity<ProblemDetail> bad(Exception e,HttpServletRequest r){return ResponseEntity.badRequest().body(problem(400,"INVALID_REQUEST",e.getMessage(),r));}
 @ExceptionHandler(InvalidDraftException.class)ResponseEntity<ProblemDetail> invalidDraft(Exception e,HttpServletRequest r){return ResponseEntity.unprocessableEntity().body(problem(422,"INVALID_DRAFT_RELATION","Participantes o asignaciones no son válidos",r));}
 @ExceptionHandler(InvalidCompanyNameException.class)ResponseEntity<ProblemDetail> invalidCompany(Exception e,HttpServletRequest r){var p=problem(422,"INVALID_COMPANY_NAME","La empresa debe contener entre 2 y 150 caracteres y no puede ser N/A",r);p.setProperty("field","companyName");return ResponseEntity.unprocessableEntity().body(p);}
 private ProblemDetail problem(int s,String c,String d,HttpServletRequest r){var p=ProblemDetail.forStatusAndDetail(HttpStatusCode.valueOf(s),d);p.setType(URI.create("https://netec.com/errors/"+c.toLowerCase(Locale.ROOT).replace('_','-')));p.setTitle(d);p.setInstance(URI.create(r.getRequestURI()));p.setProperty("code",c);p.setProperty("timestamp",Instant.now());p.setProperty("correlationId",Objects.requireNonNullElse(r.getHeader("X-Correlation-Id"),UUID.randomUUID().toString()));return p;}
}
