package com.netec.exams.notification.infrastructure.graph;

import com.netec.exams.notification.application.ApprovalNotificationSender;
import com.netec.exams.notification.infrastructure.outbox.NotificationOutbox;
import com.netec.exams.notification.infrastructure.template.ApprovalEmailTemplateRenderer;
import java.net.URI; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.util.Map; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.MediaType; import org.springframework.stereotype.Component; import org.springframework.util.LinkedMultiValueMap; import org.springframework.web.client.RestClient;
@Component class MicrosoftGraphApprovalNotificationSender implements ApprovalNotificationSender { private final RestClient http=RestClient.builder().build(); private final String tenant,clientId,secret,baseUrl; private final boolean enabled;
 MicrosoftGraphApprovalNotificationSender(@Value("${app.entra.tenant-id:}") String tenant,@Value("${app.entra.backend-client-id:}") String clientId,@Value("${app.entra.backend-client-secret:}") String secret,@Value("${app.notifications.graph-base-url:https://graph.microsoft.com/v1.0}") String baseUrl,@Value("${app.notifications.graph-mail-enabled:false}") boolean enabled){this.tenant=tenant;this.clientId=clientId;this.secret=secret;this.baseUrl=baseUrl;this.enabled=enabled;}
 public void send(NotificationOutbox n,ApprovalEmailTemplateRenderer.RenderedEmail rendered){if(!enabled)throw new IllegalStateException("GRAPH_MAIL_DISABLED");if(tenant.isBlank()||clientId.isBlank()||secret.isBlank())throw new IllegalStateException("GRAPH_CONFIGURATION_MISSING");var form=new LinkedMultiValueMap<String,String>();form.add("client_id",clientId);form.add("client_secret",secret);form.add("scope","https://graph.microsoft.com/.default");form.add("grant_type","client_credentials");var token=http.post().uri(URI.create("https://login.microsoftonline.com/"+tenant+"/oauth2/v2.0/token")).contentType(MediaType.APPLICATION_FORM_URLENCODED).body(form).retrieve().body(Map.class);var access=String.valueOf(token.get("access_token"));var message=Map.of("message",Map.of("subject",n.subject(),"body",Map.of("contentType","HTML","content",rendered.html()),"toRecipients",java.util.List.of(Map.of("emailAddress",Map.of("address",n.recipient()))),"ccRecipients",java.util.List.of(Map.of("emailAddress",Map.of("address",n.cc())))),"saveToSentItems",false);var sender=URLEncoder.encode(n.senderUpnSnapshot(),StandardCharsets.UTF_8).replace("+","%20");var endpoint=baseUrl.replaceAll("/+$","")+"/users/"+sender+"/sendMail";http.post().uri(URI.create(endpoint)).headers(h->h.setBearerAuth(access)).contentType(MediaType.APPLICATION_JSON).body(message).retrieve().toBodilessEntity();}
}
