ALTER TABLE exam_request ADD COLUMN IF NOT EXISTS course_type VARCHAR(120);
ALTER TABLE exam_request ADD COLUMN IF NOT EXISTS segment VARCHAR(120);
ALTER TABLE exam_request ADD COLUMN IF NOT EXISTS cost_center VARCHAR(160);
