package com.netec.exams.examrequest;
import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.netec.exams.catalog.ExamCatalogRepository;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.junit.jupiter.Testcontainers;
@SpringBootTest(properties={"spring.datasource.url=jdbc:tc:postgresql:16-alpine:///portal","spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver"})@AutoConfigureMockMvc@ActiveProfiles("local")@Testcontainers
class ExamRequestControllerTest{@Autowired MockMvc mvc;@Autowired ExamCatalogRepository catalog;@Autowired ParticipantExamAssignmentRepository assignments;
 @Test void createsDraftWithAuthenticatedRequesterAsSalesAdvisor()throws Exception{mvc.perform(post("/api/v1/exam-requests").contentType("application/json").content("{\"scheduledCourseCode\":\"EVT-1\"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.status").value("BORRADOR")).andExpect(jsonPath("$.requester.id").value("local-sales-001")).andExpect(jsonPath("$.salesAdvisor.id").value("local-sales-001")).andExpect(jsonPath("$.salesAdvisor.name").value("Asesor Local"));}
 @Test void rejectsManipulatedSalesAdvisorFieldsOutsideTheContract()throws Exception{mvc.perform(post("/api/v1/exam-requests").contentType("application/json").content("{\"salesAdvisorId\":\"other\",\"salesAdvisorName\":\"Other\",\"salesAdvisorUpn\":\"other@example.com\"}")).andExpect(status().isBadRequest());}
 @Test void listsImportedCatalogAndPersistsAssignment()throws Exception{var exam=catalog.findAll().get(0);var participant="10000000-0000-0000-0000-000000000001";mvc.perform(get("/api/v1/exam-catalog").param("size","10")).andExpect(status().isOk()).andExpect(jsonPath("$.content").isArray());mvc.perform(post("/api/v1/exam-requests").contentType("application/json").content("{\"participants\":[{\"id\":\""+participant+"\",\"firstName\":\"Ana\",\"lastName\":\"López\",\"email\":\"ana@netec.com\"}],\"examAssignments\":[{\"examCatalogId\":\""+exam.id()+"\",\"participantIds\":[\""+participant+"\"]}]}")).andExpect(status().isCreated());assertThat(assignments.count()).isEqualTo(1);}
 @Test void normalizesAndRestoresCompanySnapshot()throws Exception{var result=mvc.perform(post("/api/v1/exam-requests").contentType("application/json").content("{\"companyName\":\"  Mi   Empresa, S.A.  \"}")).andExpect(status().isCreated()).andExpect(jsonPath("$.companyNameSnapshot").value("Mi Empresa, S.A.")).andReturn();var location=result.getResponse().getHeader("Location");mvc.perform(get(location)).andExpect(status().isOk()).andExpect(jsonPath("$.companyNameSnapshot").value("Mi Empresa, S.A."));}
 @Test void allowsMissingCompanyInDraftAndRejectsInvalidProvidedValue()throws Exception{mvc.perform(post("/api/v1/exam-requests").contentType("application/json").content("{}")).andExpect(status().isCreated()).andExpect(jsonPath("$.companyNameSnapshot").doesNotExist());mvc.perform(post("/api/v1/exam-requests").contentType("application/json").content("{\"companyName\":\"N/A\"}")).andExpect(status().isUnprocessableEntity()).andExpect(jsonPath("$.code").value("INVALID_COMPANY_NAME")).andExpect(jsonPath("$.field").value("companyName"));}
}
