package com.netec.exams.examrequest;
import static org.assertj.core.api.Assertions.*;import static org.mockito.Mockito.*;import com.netec.exams.audit.*;import com.netec.exams.catalog.infrastructure.persistence.entity.*;import com.netec.exams.catalog.infrastructure.persistence.repository.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;
class ExamRequestServiceTest {ExamRequestRepository repository=mock(ExamRequestRepository.class);AuditRepository audit=mock(AuditRepository.class);ExamRequestParticipantRepository participants=mock(ExamRequestParticipantRepository.class);ParticipantExamAssignmentRepository assignments=mock(ParticipantExamAssignmentRepository.class);ExamCatalogRepository catalog=mock(ExamCatalogRepository.class);Clock clock=Clock.fixed(Instant.parse("2026-07-21T18:00:00Z"),ZoneOffset.UTC);ExamRequestService service=new ExamRequestService(repository,audit,participants,assignments,catalog,clock);
 @Test void createsDraftWithRequesterAndSalesAdvisorFromSecurityContext(){when(repository.save(any())).thenAnswer(i->i.getArgument(0));var result=service.create(new Requester("oid","Ana","ana@example.com","Ventas","CN"),new DraftCommand(" EVT-1 ",null,null," Nota ",List.of(),List.of()));assertThat(result.status()).isEqualTo(ExamRequestStatus.BORRADOR);assertThat(result.requester().id()).isEqualTo("oid");assertThat(result.salesAdvisor()).extracting(SalesAdvisorView::id,SalesAdvisorView::name,SalesAdvisorView::userPrincipalName).containsExactly("oid","Ana","ana@example.com");assertThat(result.scheduledCourseCode()).isEqualTo("EVT-1");verify(audit).save(any());}
 @Test void persistsAssignmentUsingCatalogSnapshot(){var participantId=UUID.randomUUID();var exam=ExamCatalogItem.imported(UUID.randomUUID(),"Microsoft","Azure","AZ-900","Azure Fundamentals","No incluido",new java.math.BigDecimal("59"),null,"key",3,clock.instant());when(repository.save(any())).thenAnswer(i->i.getArgument(0));when(catalog.findById(exam.id())).thenReturn(Optional.of(exam));service.create(new Requester("oid","Ana","ana@example.com","Ventas","CN"),new DraftCommand(null,null,null,null,List.of(new ParticipantInput(participantId,"Ana","López",null,"ana@netec.com",null,null,null)),List.of(new ExamAssignmentInput(exam.id(),List.of(participantId)))));verify(participants).saveAll(argThat(values->values.iterator().hasNext()));verify(assignments).saveAll(argThat(values->values.iterator().hasNext()));}
 @Test void normalizesAndPersistsCompanySnapshot(){when(repository.save(any())).thenAnswer(i->i.getArgument(0));var result=service.create(new Requester("oid","Ana","ana@example.com","Ventas","CN"),new DraftCommand(null,"  Mi   Empresa, S.A.  ",null,null,List.of(),List.of()));assertThat(result.companyNameSnapshot()).isEqualTo("Mi Empresa, S.A.");}
 @Test void rejectsInvalidCompanyWhenProvided(){assertThatThrownBy(()->service.create(new Requester("oid","Ana","ana@example.com","Ventas","CN"),new DraftCommand(null,"N/A",null,null,List.of(),List.of()))).isInstanceOf(InvalidCompanyNameException.class);}
 @Test void hidesRequestsOwnedByAnotherUser(){var id=UUID.randomUUID();when(repository.findByIdAndRequesterId(id,"mine")).thenReturn(Optional.empty());assertThatThrownBy(()->service.get(id,new Requester("mine","A","a@x","",""))).isInstanceOf(NotFoundException.class);}}

